/**
 * Database schema using Drizzle ORM.
 * Matches the schema defined in docs/database/schema.md
 */
export declare const tenants: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "tenants";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "tenants";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        name: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "name";
            tableName: "tenants";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        slug: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "slug";
            tableName: "tenants";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        plan: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "plan";
            tableName: "tenants";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "professional" | "essential" | "enterprise";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["essential", "professional", "enterprise"];
            baseColumn: never;
        }, object>;
        settings: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "settings";
            tableName: "tenants";
            dataType: "json";
            columnType: "MySqlJson";
            data: Record<string, unknown>;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        stripe_customer_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "stripe_customer_id";
            tableName: "tenants";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        stripe_subscription_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "stripe_subscription_id";
            tableName: "tenants";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        status: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "status";
            tableName: "tenants";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "active" | "suspended" | "cancelled";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["active", "suspended", "cancelled"];
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "tenants";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        updated_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "updated_at";
            tableName: "tenants";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        deleted_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "deleted_at";
            tableName: "tenants";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const users: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "users";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        tenant_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "tenant_id";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        email: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "email";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        password_hash: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "password_hash";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        name: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "name";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        role: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "role";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "admin" | "auditor" | "manager" | "viewer" | "module_operator";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["admin", "auditor", "manager", "viewer", "module_operator"];
            baseColumn: never;
        }, object>;
        status: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "status";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "active" | "inactive" | "pending";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["pending", "active", "inactive"];
            baseColumn: never;
        }, object>;
        mfa_enabled: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "mfa_enabled";
            tableName: "users";
            dataType: "boolean";
            columnType: "MySqlBoolean";
            data: boolean;
            driverParam: number | boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        mfa_secret: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "mfa_secret";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        google_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "google_id";
            tableName: "users";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        last_login: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "last_login";
            tableName: "users";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "users";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        updated_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "updated_at";
            tableName: "users";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        deleted_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "deleted_at";
            tableName: "users";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const userPermissions: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "user_permissions";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "user_permissions";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        user_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "user_id";
            tableName: "user_permissions";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        permission: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "permission";
            tableName: "user_permissions";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        granted_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "granted_at";
            tableName: "user_permissions";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        granted_by: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "granted_by";
            tableName: "user_permissions";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const modules: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "modules";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "modules";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        name_i18n_key: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "name_i18n_key";
            tableName: "modules";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        description_i18n_key: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "description_i18n_key";
            tableName: "modules";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        version: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "version";
            tableName: "modules";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        author: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "author";
            tableName: "modules";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        manifest: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "manifest";
            tableName: "modules";
            dataType: "json";
            columnType: "MySqlJson";
            data: Record<string, unknown>;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        status: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "status";
            tableName: "modules";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "available" | "deprecated" | "removed";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["available", "deprecated", "removed"];
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "modules";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        updated_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "updated_at";
            tableName: "modules";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const tenantModules: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "tenant_modules";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "tenant_modules";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        tenant_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "tenant_id";
            tableName: "tenant_modules";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        module_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "module_id";
            tableName: "tenant_modules";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        status: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "status";
            tableName: "tenant_modules";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "error" | "active" | "inactive";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["active", "inactive", "error"];
            baseColumn: never;
        }, object>;
        config: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "config";
            tableName: "tenant_modules";
            dataType: "json";
            columnType: "MySqlJson";
            data: Record<string, unknown>;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        installed_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "installed_at";
            tableName: "tenant_modules";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        activated_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "activated_at";
            tableName: "tenant_modules";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        deactivated_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "deactivated_at";
            tableName: "tenant_modules";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const risks: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "risks";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        tenant_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "tenant_id";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        module_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "module_id";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        detector_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "detector_id";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        title_i18n_key: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "title_i18n_key";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        description_i18n_key: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "description_i18n_key";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        severity: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "severity";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "low" | "medium" | "high" | "critical";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["low", "medium", "high", "critical"];
            baseColumn: never;
        }, object>;
        status: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "status";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "new" | "acknowledged" | "mitigated" | "resolved" | "false_positive";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["new", "acknowledged", "mitigated", "resolved", "false_positive"];
            baseColumn: never;
        }, object>;
        category: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "category";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "payroll" | "legal" | "security" | "ops" | "finance" | "compliance";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["legal", "payroll", "security", "ops", "finance", "compliance"];
            baseColumn: never;
        }, object>;
        likelihood: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "likelihood";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlDecimal";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        impact_eur: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "impact_eur";
            tableName: "risks";
            dataType: "number";
            columnType: "MySqlInt";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        entities: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "entities";
            tableName: "risks";
            dataType: "json";
            columnType: "MySqlJson";
            data: {
                type: string;
                id: string;
                name?: string;
            }[];
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        evidence: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "evidence";
            tableName: "risks";
            dataType: "json";
            columnType: "MySqlJson";
            data: {
                type: string;
                ref: string;
                label?: string;
            }[];
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        recommended_actions_i18n_key: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "recommended_actions_i18n_key";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        assigned_to: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "assigned_to";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        detected_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "detected_at";
            tableName: "risks";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        acknowledged_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "acknowledged_at";
            tableName: "risks";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        acknowledged_by: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "acknowledged_by";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        resolved_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "resolved_at";
            tableName: "risks";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        resolved_by: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "resolved_by";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        resolution_notes: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "resolution_notes";
            tableName: "risks";
            dataType: "string";
            columnType: "MySqlText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "risks";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        updated_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "updated_at";
            tableName: "risks";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        deleted_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "deleted_at";
            tableName: "risks";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const riskHistory: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "risk_history";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "risk_history";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        risk_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "risk_id";
            tableName: "risk_history";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        action: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "action";
            tableName: "risk_history";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        actor_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "actor_id";
            tableName: "risk_history";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        changes: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "changes";
            tableName: "risk_history";
            dataType: "json";
            columnType: "MySqlJson";
            data: Record<string, {
                from?: unknown;
                to?: unknown;
            }>;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        notes: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "notes";
            tableName: "risk_history";
            dataType: "string";
            columnType: "MySqlText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        timestamp: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "timestamp";
            tableName: "risk_history";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const auditLogs: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "audit_logs";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        tenant_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "tenant_id";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        actor_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "actor_id";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        actor_email: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "actor_email";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        action: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "action";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        resource_type: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "resource_type";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        resource_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "resource_id";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        method: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "method";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        path: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "path";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        ip_address: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "ip_address";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        user_agent: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "user_agent";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        request_body: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "request_body";
            tableName: "audit_logs";
            dataType: "json";
            columnType: "MySqlJson";
            data: unknown;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        response_status: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "response_status";
            tableName: "audit_logs";
            dataType: "number";
            columnType: "MySqlInt";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        changes: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "changes";
            tableName: "audit_logs";
            dataType: "json";
            columnType: "MySqlJson";
            data: Record<string, {
                from?: unknown;
                to?: unknown;
            }>;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        event_hash: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "event_hash";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        anchor_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "anchor_id";
            tableName: "audit_logs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        timestamp: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "timestamp";
            tableName: "audit_logs";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const blockchainAnchors: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "blockchain_anchors";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "blockchain_anchors";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        merkle_root: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "merkle_root";
            tableName: "blockchain_anchors";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        tx_hash: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "tx_hash";
            tableName: "blockchain_anchors";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        block_number: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "block_number";
            tableName: "blockchain_anchors";
            dataType: "number";
            columnType: "MySqlInt";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        chain_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "chain_id";
            tableName: "blockchain_anchors";
            dataType: "number";
            columnType: "MySqlInt";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        event_count: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "event_count";
            tableName: "blockchain_anchors";
            dataType: "number";
            columnType: "MySqlInt";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        status: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "status";
            tableName: "blockchain_anchors";
            dataType: "string";
            columnType: "MySqlEnumColumn";
            data: "pending" | "confirmed" | "failed";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["pending", "confirmed", "failed"];
            baseColumn: never;
        }, object>;
        anchored_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "anchored_at";
            tableName: "blockchain_anchors";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "blockchain_anchors";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const auditLogProofs: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "audit_log_proofs";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "audit_log_proofs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        audit_log_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "audit_log_id";
            tableName: "audit_log_proofs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        anchor_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "anchor_id";
            tableName: "audit_log_proofs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        leaf_hash: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "leaf_hash";
            tableName: "audit_log_proofs";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        proof: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "proof";
            tableName: "audit_log_proofs";
            dataType: "json";
            columnType: "MySqlJson";
            data: string[];
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        positions: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "positions";
            tableName: "audit_log_proofs";
            dataType: "json";
            columnType: "MySqlJson";
            data: ("left" | "right")[];
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "audit_log_proofs";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const sessions: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "sessions";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "sessions";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        user_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "user_id";
            tableName: "sessions";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        token_hash: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "token_hash";
            tableName: "sessions";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        ip_address: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "ip_address";
            tableName: "sessions";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        user_agent: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "user_agent";
            tableName: "sessions";
            dataType: "string";
            columnType: "MySqlText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        expires_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "expires_at";
            tableName: "sessions";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "sessions";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        revoked_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "revoked_at";
            tableName: "sessions";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const apiKeys: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "api_keys";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "api_keys";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        tenant_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "tenant_id";
            tableName: "api_keys";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        name: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "name";
            tableName: "api_keys";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        key_hash: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "key_hash";
            tableName: "api_keys";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        key_prefix: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "key_prefix";
            tableName: "api_keys";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        permissions: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "permissions";
            tableName: "api_keys";
            dataType: "json";
            columnType: "MySqlJson";
            data: string[];
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        last_used: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "last_used";
            tableName: "api_keys";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        expires_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "expires_at";
            tableName: "api_keys";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "api_keys";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        revoked_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "revoked_at";
            tableName: "api_keys";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
export declare const notifications: import("drizzle-orm/mysql-core").MySqlTableWithColumns<{
    name: "notifications";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "id";
            tableName: "notifications";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        user_id: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "user_id";
            tableName: "notifications";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        type: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "type";
            tableName: "notifications";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        title_i18n_key: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "title_i18n_key";
            tableName: "notifications";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        body_i18n_key: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "body_i18n_key";
            tableName: "notifications";
            dataType: "string";
            columnType: "MySqlVarChar";
            data: string;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, object>;
        data: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "data";
            tableName: "notifications";
            dataType: "json";
            columnType: "MySqlJson";
            data: Record<string, unknown>;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        read_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "read_at";
            tableName: "notifications";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
        created_at: import("drizzle-orm/mysql-core").MySqlColumn<{
            name: "created_at";
            tableName: "notifications";
            dataType: "date";
            columnType: "MySqlTimestamp";
            data: Date;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, object>;
    };
    dialect: "mysql";
}>;
//# sourceMappingURL=schema.d.ts.map